require("plugins.theme") -- Must be first when loading
require("plugins.lsp-config") -- Must be before blink
require("plugins.blink")
require("plugins.comment")
require("plugins.dart")
require("plugins.dashboard")
require("plugins.devicons")
require("plugins.flash")
require("plugins.flash")
require("plugins.fugitive")
require("plugins.fzf")
require("plugins.gitsigns")
require("plugins.indent-lines")
require("plugins.java")
require("plugins.lualine")
require("plugins.neogen")
require("plugins.nvim-dap")
require("plugins.nvim-tree")
require("plugins.tmux")
require("plugins.treesitter")
require("plugins.undotree")
